title: "Essential cooking"
description: "The normal rotation of foods from our home"
baseurl: "/cookbook"
url: "https://jensenrf.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  recipes:
    output: true
    permalink: /recipes/:name/

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
